export const PRODUCT_CATEGORIES = [
    'All',
    'Favourites',
    'Baby Shower',
    'Bouquet Candle',
    'Cake / Dessert Candle',
    'Christmas',
    'Coconut Shell Candle',
    'Concrete Base Candle',
    'Diwali',
    'Figure Candle',
    'Glass Jar Candle',
    'Hampers | Combo',
    'Halloween | Fall',
    'Ladoo Candle',
    'Pillar Candle',
    'Rakhi',
    'Tealight',
    'Tin Jar Candle',
    'Urli Candle',
    'Valentines',
    'Wax Melts',
    'Wax Sachet',
    'Wooden Base Candle'
];
